import sys
from collections.abc import Mapping
from typing import Final

errorcode: Mapping[int, str]

EPERM: Final[Literal[1]]
ENOENT: Final[Literal[2]]
ESRCH: Final[Literal[3]]
EINTR: Final[Literal[4]]
EIO: Final[Literal[5]]
ENXIO: Final[Literal[6]]
E2BIG: Final[Literal[7]]
ENOEXEC: Final[Literal[8]]
EBADF: Final[Literal[9]]
ECHILD: Final[Literal[10]]
EAGAIN: Final[Literal[11]]
ENOMEM: Final[Literal[12]]
EACCES: Final[Literal[13]]
EFAULT: Final[Literal[14]]
EBUSY: Final[Literal[16]]
EEXIST: Final[Literal[17]]
EXDEV: Final[Literal[18]]
ENODEV: Final[Literal[19]]
ENOTDIR: Final[Literal[20]]
EISDIR: Final[Literal[21]]
EINVAL: Final[Literal[22]]
ENFILE: Final[Literal[23]]
EMFILE: Final[Literal[24]]
ENOTTY: Final[Literal[25]]
ETXTBSY: Final[Literal[26]]
EFBIG: Final[Literal[27]]
ENOSPC: Final[Literal[28]]
ESPIPE: Final[Literal[29]]
EROFS: Final[Literal[30]]
EMLINK: Final[Literal[31]]
EPIPE: Final[Literal[32]]
EDOM: Final[Literal[33]]
ERANGE: Final[Literal[34]]
EDEADLK: Final[Literal[35]]
ENAMETOOLONG: Final[Literal[36]]
ENOLCK: Final[Literal[37]]
ENOSYS: Final[Literal[38]]
ENOTEMPTY: Final[Literal[39]]
ELOOP: Final[Literal[40]]
EWOULDBLOCK: Final[Literal[11]]
ENOMSG: Final[Literal[42]]
EIDRM: Final[Literal[43]]
ENOSTR: Final[Literal[60]]
ENODATA: Final[Literal[61]]
ETIME: Final[Literal[62]]
ENOSR: Final[Literal[63]]
EREMOTE: Final[Literal[66]]
ENOLINK: Final[Literal[67]]
EPROTO: Final[Literal[71]]
EBADMSG: Final[Literal[74]]
EOVERFLOW: Final[Literal[75]]
EILSEQ: Final[Literal[84]]
EUSERS: Final[Literal[87]]
ENOTSOCK: Final[Literal[88]]
EDESTADDRREQ: Final[Literal[89]]
EMSGSIZE: Final[Literal[90]]
EPROTOTYPE: Final[Literal[91]]
ENOPROTOOPT: Final[Literal[92]]
EPROTONOSUPPORT: Final[Literal[93]]
ESOCKTNOSUPPORT: Final[Literal[94]]
ENOTSUP: Final[Literal[95]]
EOPNOTSUPP: Final[Literal[95]]
EPFNOSUPPORT: Final[Literal[96]]
EAFNOSUPPORT: Final[Literal[97]]
EADDRINUSE: Final[Literal[98]]
EADDRNOTAVAIL: Final[Literal[99]]
ENETDOWN: Final[Literal[100]]
ENETUNREACH: Final[Literal[101]]
ENETRESET: Final[Literal[102]]
ECONNABORTED: Final[Literal[103]]
ECONNRESET: Final[Literal[104]]
ENOBUFS: Final[Literal[105]]
EISCONN: Final[Literal[106]]
ENOTCONN: Final[Literal[107]]
ESHUTDOWN: Final[Literal[108]]
ETOOMANYREFS: Final[Literal[109]]
ETIMEDOUT: Final[Literal[110]]
ECONNREFUSED: Final[Literal[111]]
EHOSTDOWN: Final[Literal[112]]
EHOSTUNREACH: Final[Literal[113]]
EALREADY: Final[Literal[114]]
EINPROGRESS: Final[Literal[115]]
ESTALE: Final[Literal[116]]
EDQUOT: Final[Literal[122]]
ECANCELED: Final[Literal[125]]  # undocumented
ENOTRECOVERABLE: Final[Literal[131]]  # undocumented
EOWNERDEAD: Final[Literal[130]]  # undocumented

if sys.platform == "sunos5" or sys.platform == "solaris":  # noqa: Y008
    ELOCKUNMAPPED: Final[int]
    ENOTACTIVE: Final[int]

if sys.platform != "win32":
    ENOTBLK: Final[Literal[15]]
    EMULTIHOP: Final[Literal[72]]

if sys.platform == "darwin":
    # All of the below are undocumented
    EAUTH: Final[int]
    EBADARCH: Final[int]
    EBADEXEC: Final[int]
    EBADMACHO: Final[int]
    EBADRPC: Final[int]
    EDEVERR: Final[int]
    EFTYPE: Final[int]
    ENEEDAUTH: Final[int]
    ENOATTR: Final[int]
    ENOPOLICY: Final[int]
    EPROCLIM: Final[int]
    EPROCUNAVAIL: Final[int]
    EPROGMISMATCH: Final[int]
    EPROGUNAVAIL: Final[int]
    EPWROFF: Final[int]
    ERPCMISMATCH: Final[int]
    ESHLIBVERS: Final[int]
    if sys.version_info >= (3, 11):
        EQFULL: Final[int]
        ENOTCAPABLE: Final[int]  # available starting with 3.11.1

if sys.platform != "darwin":
    EDEADLOCK: Final[Literal[35]]

if sys.platform != "win32" and sys.platform != "darwin":
    ECHRNG: Final[Literal[44]]
    EL2NSYNC: Final[Literal[45]]
    EL3HLT: Final[Literal[46]]
    EL3RST: Final[Literal[47]]
    ELNRNG: Final[Literal[48]]
    EUNATCH: Final[Literal[49]]
    ENOCSI: Final[Literal[50]]
    EL2HLT: Final[Literal[51]]
    EBADE: Final[Literal[52]]
    EBADR: Final[Literal[53]]
    EXFULL: Final[Literal[54]]
    ENOANO: Final[Literal[55]]
    EBADRQC: Final[Literal[56]]
    EBADSLT: Final[Literal[57]]
    EBFONT: Final[Literal[59]]
    ENONET: Final[Literal[64]]
    ENOPKG: Final[Literal[65]]
    EADV: Final[Literal[68]]
    ESRMNT: Final[Literal[69]]
    ECOMM: Final[Literal[70]]
    EDOTDOT: Final[Literal[73]]
    ENOTUNIQ: Final[Literal[76]]
    EBADFD: Final[Literal[77]]
    EREMCHG: Final[Literal[78]]
    ELIBACC: Final[Literal[79]]
    ELIBBAD: Final[Literal[80]]
    ELIBSCN: Final[Literal[81]]
    ELIBMAX: Final[Literal[82]]
    ELIBEXEC: Final[Literal[83]]
    ERESTART: Final[Literal[85]]
    ESTRPIPE: Final[Literal[86]]
    EUCLEAN: Final[Literal[117]]
    ENOTNAM: Final[Literal[118]]
    ENAVAIL: Final[Literal[119]]
    EISNAM: Final[Literal[120]]
    EREMOTEIO: Final[Literal[5]]
    # All of the below are undocumented
    EKEYEXPIRED: Final[Literal[127]]
    EKEYREJECTED: Final[Literal[129]]
    EKEYREVOKED: Final[Literal[128]]
    EMEDIUMTYPE: Final[Literal[124]]
    ENOKEY: Final[Literal[126]]
    ENOMEDIUM: Final[Literal[123]]
    ERFKILL: Final[Literal[132]]

    if sys.version_info >= (3, 14):
        EHWPOISON: Final[Literal[133]]

if sys.platform == "win32":
    # All of these are undocumented
    WSABASEERR: Final[int]
    WSAEACCES: Final[Literal[13]]
    WSAEADDRINUSE: Final[Literal[98]]
    WSAEADDRNOTAVAIL: Final[Literal[99]]
    WSAEAFNOSUPPORT: Final[Literal[97]]
    WSAEALREADY: Final[Literal[114]]
    WSAEBADF: Final[Literal[9]]
    WSAECONNABORTED: Final[Literal[103]]
    WSAECONNREFUSED: Final[Literal[111]]
    WSAECONNRESET: Final[Literal[104]]
    WSAEDESTADDRREQ: Final[Literal[89]]
    WSAEDISCON: Final[int]
    WSAEDQUOT: Final[Literal[122]]
    WSAEFAULT: Final[Literal[14]]
    WSAEHOSTDOWN: Final[Literal[112]]
    WSAEHOSTUNREACH: Final[Literal[113]]
    WSAEINPROGRESS: Final[Literal[115]]
    WSAEINTR: Final[Literal[4]]
    WSAEINVAL: Final[Literal[22]]
    WSAEISCONN: Final[Literal[106]]
    WSAELOOP: Final[Literal[40]]
    WSAEMFILE: Final[Literal[24]]
    WSAEMSGSIZE: Final[Literal[90]]
    WSAENAMETOOLONG: Final[Literal[36]]
    WSAENETDOWN: Final[Literal[100]]
    WSAENETRESET: Final[Literal[102]]
    WSAENETUNREACH: Final[Literal[101]]
    WSAENOBUFS: Final[Literal[105]]
    WSAENOPROTOOPT: Final[Literal[92]]
    WSAENOTCONN: Final[Literal[107]]
    WSAENOTEMPTY: Final[Literal[39]]
    WSAENOTSOCK: Final[Literal[88]]
    WSAEOPNOTSUPP: Final[Literal[95]]
    WSAEPFNOSUPPORT: Final[Literal[96]]
    WSAEPROCLIM: Final[int]
    WSAEPROTONOSUPPORT: Final[Literal[93]]
    WSAEPROTOTYPE: Final[Literal[91]]
    WSAEREMOTE: Final[Literal[66]]
    WSAESHUTDOWN: Final[Literal[108]]
    WSAESOCKTNOSUPPORT: Final[Literal[94]]
    WSAESTALE: Final[Literal[116]]
    WSAETIMEDOUT: Final[Literal[110]]
    WSAETOOMANYREFS: Final[Literal[109]]
    WSAEUSERS: Final[Literal[87]]
    WSAEWOULDBLOCK: Final[Literal[11]]
    WSANOTINITIALISED: Final[int]
    WSASYSNOTREADY: Final[int]
    WSAVERNOTSUPPORTED: Final[int]
