import sys
from collections.abc import Mapping
from typing import Final

errorcode: Mapping[int, str]

EPERM: Final[Literal[1]]
ENOENT: Final[Literal[2]]
ESRCH: Final[Literal[3]]
EINTR: Final[Literal[4]]
EIO: Final[Literal[5]]
ENXIO: Final[Literal[6]]
E2BIG: Final[Literal[7]]
ENOEXEC: Final[Literal[8]]
EBADF: Final[Literal[9]]
ECHILD: Final[Literal[10]]
EAGAIN: Final[Literal[35]]
ENOMEM: Final[Literal[12]]
EACCES: Final[Literal[13]]
EFAULT: Final[Literal[14]]
EBUSY: Final[Literal[16]]
EEXIST: Final[Literal[17]]
EXDEV: Final[Literal[18]]
ENODEV: Final[Literal[19]]
ENOTDIR: Final[Literal[20]]
EISDIR: Final[Literal[21]]
EINVAL: Final[Literal[22]]
ENFILE: Final[Literal[23]]
EMFILE: Final[Literal[24]]
ENOTTY: Final[Literal[25]]
ETXTBSY: Final[Literal[26]]
EFBIG: Final[Literal[27]]
ENOSPC: Final[Literal[28]]
ESPIPE: Final[Literal[29]]
EROFS: Final[Literal[30]]
EMLINK: Final[Literal[31]]
EPIPE: Final[Literal[32]]
EDOM: Final[Literal[33]]
ERANGE: Final[Literal[34]]
EDEADLK: Final[Literal[11]]
ENAMETOOLONG: Final[Literal[63]]
ENOLCK: Final[Literal[77]]
ENOSYS: Final[Literal[78]]
ENOTEMPTY: Final[Literal[66]]
ELOOP: Final[Literal[62]]
EWOULDBLOCK: Final[Literal[35]]
ENOMSG: Final[Literal[91]]
EIDRM: Final[Literal[90]]
ENOSTR: Final[Literal[99]]
ENODATA: Final[Literal[96]]
ETIME: Final[Literal[101]]
ENOSR: Final[Literal[98]]
EREMOTE: Final[Literal[71]]
ENOLINK: Final[Literal[97]]
EPROTO: Final[Literal[100]]
EBADMSG: Final[Literal[94]]
EOVERFLOW: Final[Literal[84]]
EILSEQ: Final[Literal[92]]
EUSERS: Final[Literal[68]]
ENOTSOCK: Final[Literal[38]]
EDESTADDRREQ: Final[Literal[39]]
EMSGSIZE: Final[Literal[40]]
EPROTOTYPE: Final[Literal[41]]
ENOPROTOOPT: Final[Literal[42]]
EPROTONOSUPPORT: Final[Literal[43]]
ESOCKTNOSUPPORT: Final[Literal[44]]
ENOTSUP: Final[Literal[45]]
EOPNOTSUPP: Final[Literal[102]]
EPFNOSUPPORT: Final[Literal[46]]
EAFNOSUPPORT: Final[Literal[47]]
EADDRINUSE: Final[Literal[48]]
EADDRNOTAVAIL: Final[Literal[49]]
ENETDOWN: Final[Literal[50]]
ENETUNREACH: Final[Literal[51]]
ENETRESET: Final[Literal[52]]
ECONNABORTED: Final[Literal[53]]
ECONNRESET: Final[Literal[54]]
ENOBUFS: Final[Literal[55]]
EISCONN: Final[Literal[56]]
ENOTCONN: Final[Literal[57]]
ESHUTDOWN: Final[Literal[58]]
ETOOMANYREFS: Final[Literal[59]]
ETIMEDOUT: Final[Literal[60]]
ECONNREFUSED: Final[Literal[61]]
EHOSTDOWN: Final[Literal[64]]
EHOSTUNREACH: Final[Literal[65]]
EALREADY: Final[Literal[37]]
EINPROGRESS: Final[Literal[36]]
ESTALE: Final[Literal[70]]
EDQUOT: Final[Literal[69]]
ECANCELED: Final[Literal[89]]  # undocumented
ENOTRECOVERABLE: Final[Literal[104]]  # undocumented
EOWNERDEAD: Final[Literal[105]]  # undocumented

if sys.platform == "sunos5" or sys.platform == "solaris":  # noqa: Y008
    ELOCKUNMAPPED: Final[int]
    ENOTACTIVE: Final[int]

if sys.platform != "win32":
    ENOTBLK: Final[Literal[15]]
    EMULTIHOP: Final[Literal[95]]

if sys.platform == "darwin":
    # All of the below are undocumented
    EAUTH: Final[Literal[80]]
    EBADARCH: Final[Literal[86]]
    EBADEXEC: Final[Literal[85]]
    EBADMACHO: Final[Literal[88]]
    EBADRPC: Final[Literal[72]]
    EDEVERR: Final[Literal[83]]
    EFTYPE: Final[Literal[79]]
    ENEEDAUTH: Final[Literal[81]]
    ENOATTR: Final[Literal[93]]
    ENOPOLICY: Final[Literal[103]]
    EPROCLIM: Final[Literal[67]]
    EPROCUNAVAIL: Final[Literal[76]]
    EPROGMISMATCH: Final[Literal[75]]
    EPROGUNAVAIL: Final[Literal[74]]
    EPWROFF: Final[Literal[82]]
    ERPCMISMATCH: Final[Literal[73]]
    ESHLIBVERS: Final[Literal[87]]
    if sys.version_info >= (3, 11):
        EQFULL: Final[Literal[106]]
        ENOTCAPABLE: Final[Literal[107]]  # available starting with 3.11.1

if sys.platform != "darwin":
    EDEADLOCK: Final[int]

if sys.platform != "win32" and sys.platform != "darwin":
    ECHRNG: Final[int]
    EL2NSYNC: Final[int]
    EL3HLT: Final[int]
    EL3RST: Final[int]
    ELNRNG: Final[int]
    EUNATCH: Final[int]
    ENOCSI: Final[int]
    EL2HLT: Final[int]
    EBADE: Final[int]
    EBADR: Final[int]
    EXFULL: Final[int]
    ENOANO: Final[int]
    EBADRQC: Final[int]
    EBADSLT: Final[int]
    EBFONT: Final[int]
    ENONET: Final[int]
    ENOPKG: Final[int]
    EADV: Final[int]
    ESRMNT: Final[int]
    ECOMM: Final[int]
    EDOTDOT: Final[int]
    ENOTUNIQ: Final[int]
    EBADFD: Final[int]
    EREMCHG: Final[int]
    ELIBACC: Final[int]
    ELIBBAD: Final[int]
    ELIBSCN: Final[int]
    ELIBMAX: Final[int]
    ELIBEXEC: Final[int]
    ERESTART: Final[int]
    ESTRPIPE: Final[int]
    EUCLEAN: Final[int]
    ENOTNAM: Final[int]
    ENAVAIL: Final[int]
    EISNAM: Final[int]
    EREMOTEIO: Final[Literal[5]]
    # All of the below are undocumented
    EKEYEXPIRED: Final[int]
    EKEYREJECTED: Final[int]
    EKEYREVOKED: Final[int]
    EMEDIUMTYPE: Final[int]
    ENOKEY: Final[int]
    ENOMEDIUM: Final[int]
    ERFKILL: Final[int]

    if sys.version_info >= (3, 14):
        EHWPOISON: Final[int]

if sys.platform == "win32":
    # All of these are undocumented
    WSABASEERR: Final[int]
    WSAEACCES: Final[Literal[13]]
    WSAEADDRINUSE: Final[Literal[48]]
    WSAEADDRNOTAVAIL: Final[Literal[49]]
    WSAEAFNOSUPPORT: Final[Literal[47]]
    WSAEALREADY: Final[Literal[37]]
    WSAEBADF: Final[Literal[9]]
    WSAECONNABORTED: Final[Literal[53]]
    WSAECONNREFUSED: Final[Literal[61]]
    WSAECONNRESET: Final[Literal[54]]
    WSAEDESTADDRREQ: Final[Literal[39]]
    WSAEDISCON: Final[int]
    WSAEDQUOT: Final[Literal[69]]
    WSAEFAULT: Final[Literal[14]]
    WSAEHOSTDOWN: Final[Literal[64]]
    WSAEHOSTUNREACH: Final[Literal[65]]
    WSAEINPROGRESS: Final[Literal[36]]
    WSAEINTR: Final[Literal[4]]
    WSAEINVAL: Final[Literal[22]]
    WSAEISCONN: Final[Literal[56]]
    WSAELOOP: Final[Literal[62]]
    WSAEMFILE: Final[Literal[24]]
    WSAEMSGSIZE: Final[Literal[40]]
    WSAENAMETOOLONG: Final[Literal[63]]
    WSAENETDOWN: Final[Literal[50]]
    WSAENETRESET: Final[Literal[52]]
    WSAENETUNREACH: Final[Literal[51]]
    WSAENOBUFS: Final[Literal[55]]
    WSAENOPROTOOPT: Final[Literal[42]]
    WSAENOTCONN: Final[Literal[57]]
    WSAENOTEMPTY: Final[Literal[66]]
    WSAENOTSOCK: Final[Literal[38]]
    WSAEOPNOTSUPP: Final[Literal[102]]
    WSAEPFNOSUPPORT: Final[Literal[46]]
    WSAEPROCLIM: Final[Literal[67]]
    WSAEPROTONOSUPPORT: Final[Literal[43]]
    WSAEPROTOTYPE: Final[Literal[41]]
    WSAEREMOTE: Final[Literal[71]]
    WSAESHUTDOWN: Final[Literal[58]]
    WSAESOCKTNOSUPPORT: Final[Literal[44]]
    WSAESTALE: Final[Literal[70]]
    WSAETIMEDOUT: Final[Literal[60]]
    WSAETOOMANYREFS: Final[Literal[59]]
    WSAEUSERS: Final[Literal[68]]
    WSAEWOULDBLOCK: Final[Literal[35]]
    WSANOTINITIALISED: Final[int]
    WSASYSNOTREADY: Final[int]
    WSAVERNOTSUPPORTED: Final[int]

