import sys
from collections.abc import Mapping
from typing import Final

errorcode: Mapping[int, str]

EPERM: Final[Literal[1]]
ENOENT: Final[Literal[2]]
ESRCH: Final[Literal[3]]
EINTR: Final[Literal[4]]
EIO: Final[Literal[5]]
ENXIO: Final[Literal[6]]
E2BIG: Final[Literal[7]]
ENOEXEC: Final[Literal[8]]
EBADF: Final[Literal[9]]
ECHILD: Final[Literal[10]]
EAGAIN: Final[Literal[11]]
ENOMEM: Final[Literal[12]]
EACCES: Final[Literal[13]]
EFAULT: Final[Literal[14]]
EBUSY: Final[Literal[16]]
EEXIST: Final[Literal[17]]
EXDEV: Final[Literal[18]]
ENODEV: Final[Literal[19]]
ENOTDIR: Final[Literal[20]]
EISDIR: Final[Literal[21]]
EINVAL: Final[Literal[22]]
ENFILE: Final[Literal[23]]
EMFILE: Final[Literal[24]]
ENOTTY: Final[Literal[25]]
ETXTBSY: Final[Literal[139]]
EFBIG: Final[Literal[27]]
ENOSPC: Final[Literal[28]]
ESPIPE: Final[Literal[29]]
EROFS: Final[Literal[30]]
EMLINK: Final[Literal[31]]
EPIPE: Final[Literal[32]]
EDOM: Final[Literal[33]]
ERANGE: Final[Literal[34]]
EDEADLK: Final[Literal[36]]
ENAMETOOLONG: Final[Literal[38]]
ENOLCK: Final[Literal[39]]
ENOSYS: Final[Literal[40]]
ENOTEMPTY: Final[Literal[41]]
ELOOP: Final[Literal[10062]]
EWOULDBLOCK: Final[Literal[10035]]
ENOMSG: Final[Literal[122]]
EIDRM: Final[Literal[111]]
ENOSTR: Final[Literal[125]]
ENODATA: Final[Literal[120]]
ETIME: Final[Literal[137]]
ENOSR: Final[Literal[124]]
EREMOTE: Final[Literal[10071]]
ENOLINK: Final[Literal[121]]
EPROTO: Final[Literal[134]]
EBADMSG: Final[Literal[104]]
EOVERFLOW: Final[Literal[132]]
EILSEQ: Final[Literal[42]]
EUSERS: Final[Literal[10068]]
ENOTSOCK: Final[Literal[10038]]
EDESTADDRREQ: Final[Literal[10039]]
EMSGSIZE: Final[Literal[10040]]
EPROTOTYPE: Final[Literal[10041]]
ENOPROTOOPT: Final[Literal[10042]]
EPROTONOSUPPORT: Final[Literal[10043]]
ESOCKTNOSUPPORT: Final[Literal[10044]]
ENOTSUP: Final[Literal[129]]
EOPNOTSUPP: Final[Literal[10045]]
EPFNOSUPPORT: Final[Literal[10046]]
EAFNOSUPPORT: Final[Literal[10047]]
EADDRINUSE: Final[Literal[10048]]
EADDRNOTAVAIL: Final[Literal[10049]]
ENETDOWN: Final[Literal[10050]]
ENETUNREACH: Final[Literal[10051]]
ENETRESET: Final[Literal[10052]]
ECONNABORTED: Final[Literal[10053]]
ECONNRESET: Final[Literal[10054]]
ENOBUFS: Final[Literal[10055]]
EISCONN: Final[Literal[10056]]
ENOTCONN: Final[Literal[10057]]
ESHUTDOWN: Final[Literal[10058]]
ETOOMANYREFS: Final[Literal[10059]]
ETIMEDOUT: Final[Literal[10060]]
ECONNREFUSED: Final[Literal[10061]]
EHOSTDOWN: Final[Literal[10064]]
EHOSTUNREACH: Final[Literal[10065]]
EALREADY: Final[Literal[10037]]
EINPROGRESS: Final[Literal[10036]]
ESTALE: Final[Literal[10070]]
EDQUOT: Final[Literal[10069]]
ECANCELED: Final[Literal[105]]  # undocumented
ENOTRECOVERABLE: Final[Literal[127]]  # undocumented
EOWNERDEAD: Final[Literal[133]]  # undocumented

if sys.platform == "sunos5" or sys.platform == "solaris":  # noqa: Y008
    ELOCKUNMAPPED: Final[int]
    ENOTACTIVE: Final[int]

if sys.platform != "win32":
    ENOTBLK: Final[int]
    EMULTIHOP: Final[int]

if sys.platform == "darwin":
    # All of the below are undocumented
    EAUTH: Final[int]
    EBADARCH: Final[int]
    EBADEXEC: Final[int]
    EBADMACHO: Final[int]
    EBADRPC: Final[int]
    EDEVERR: Final[int]
    EFTYPE: Final[int]
    ENEEDAUTH: Final[int]
    ENOATTR: Final[int]
    ENOPOLICY: Final[int]
    EPROCLIM: Final[int]
    EPROCUNAVAIL: Final[int]
    EPROGMISMATCH: Final[int]
    EPROGUNAVAIL: Final[int]
    EPWROFF: Final[int]
    ERPCMISMATCH: Final[int]
    ESHLIBVERS: Final[int]
    if sys.version_info >= (3, 11):
        EQFULL: Final[int]
        ENOTCAPABLE: Final[int]  # available starting with 3.11.1

if sys.platform != "darwin":
    EDEADLOCK: Final[Literal[36]]

if sys.platform != "win32" and sys.platform != "darwin":
    ECHRNG: Final[int]
    EL2NSYNC: Final[int]
    EL3HLT: Final[int]
    EL3RST: Final[int]
    ELNRNG: Final[int]
    EUNATCH: Final[int]
    ENOCSI: Final[int]
    EL2HLT: Final[int]
    EBADE: Final[int]
    EBADR: Final[int]
    EXFULL: Final[int]
    ENOANO: Final[int]
    EBADRQC: Final[int]
    EBADSLT: Final[int]
    EBFONT: Final[int]
    ENONET: Final[int]
    ENOPKG: Final[int]
    EADV: Final[int]
    ESRMNT: Final[int]
    ECOMM: Final[int]
    EDOTDOT: Final[int]
    ENOTUNIQ: Final[int]
    EBADFD: Final[int]
    EREMCHG: Final[int]
    ELIBACC: Final[int]
    ELIBBAD: Final[int]
    ELIBSCN: Final[int]
    ELIBMAX: Final[int]
    ELIBEXEC: Final[int]
    ERESTART: Final[int]
    ESTRPIPE: Final[int]
    EUCLEAN: Final[int]
    ENOTNAM: Final[int]
    ENAVAIL: Final[int]
    EISNAM: Final[int]
    EREMOTEIO: Final[Literal[5]]
    # All of the below are undocumented
    EKEYEXPIRED: Final[int]
    EKEYREJECTED: Final[int]
    EKEYREVOKED: Final[int]
    EMEDIUMTYPE: Final[int]
    ENOKEY: Final[int]
    ENOMEDIUM: Final[int]
    ERFKILL: Final[int]

    if sys.version_info >= (3, 14):
        EHWPOISON: Final[int]

if sys.platform == "win32":
    # All of these are undocumented
    WSABASEERR: Final[Literal[10000]]
    WSAEACCES: Final[Literal[13]]
    WSAEADDRINUSE: Final[Literal[10048]]
    WSAEADDRNOTAVAIL: Final[Literal[10049]]
    WSAEAFNOSUPPORT: Final[Literal[10047]]
    WSAEALREADY: Final[Literal[10037]]
    WSAEBADF: Final[Literal[9]]
    WSAECONNABORTED: Final[Literal[10053]]
    WSAECONNREFUSED: Final[Literal[10061]]
    WSAECONNRESET: Final[Literal[10054]]
    WSAEDESTADDRREQ: Final[Literal[10039]]
    WSAEDISCON: Final[Literal[10101]]
    WSAEDQUOT: Final[Literal[10069]]
    WSAEFAULT: Final[Literal[14]]
    WSAEHOSTDOWN: Final[Literal[10064]]
    WSAEHOSTUNREACH: Final[Literal[10065]]
    WSAEINPROGRESS: Final[Literal[10036]]
    WSAEINTR: Final[Literal[4]]
    WSAEINVAL: Final[Literal[22]]
    WSAEISCONN: Final[Literal[10056]]
    WSAELOOP: Final[Literal[10062]]
    WSAEMFILE: Final[Literal[24]]
    WSAEMSGSIZE: Final[Literal[10040]]
    WSAENAMETOOLONG: Final[Literal[38]]
    WSAENETDOWN: Final[Literal[10050]]
    WSAENETRESET: Final[Literal[10052]]
    WSAENETUNREACH: Final[Literal[10051]]
    WSAENOBUFS: Final[Literal[10055]]
    WSAENOPROTOOPT: Final[Literal[10042]]
    WSAENOTCONN: Final[Literal[10057]]
    WSAENOTEMPTY: Final[Literal[41]]
    WSAENOTSOCK: Final[Literal[10038]]
    WSAEOPNOTSUPP: Final[Literal[10045]]
    WSAEPFNOSUPPORT: Final[Literal[10046]]
    WSAEPROCLIM: Final[Literal[10067]]
    WSAEPROTONOSUPPORT: Final[Literal[10043]]
    WSAEPROTOTYPE: Final[Literal[10041]]
    WSAEREMOTE: Final[Literal[10071]]
    WSAESHUTDOWN: Final[Literal[10058]]
    WSAESOCKTNOSUPPORT: Final[Literal[10044]]
    WSAESTALE: Final[Literal[10070]]
    WSAETIMEDOUT: Final[Literal[10060]]
    WSAETOOMANYREFS: Final[Literal[10059]]
    WSAEUSERS: Final[Literal[10068]]
    WSAEWOULDBLOCK: Final[Literal[10035]]
    WSANOTINITIALISED: Final[Literal[10093]]
    WSASYSNOTREADY: Final[Literal[10091]]
    WSAVERNOTSUPPORTED: Final[Literal[10092]]
